#ifndef GLOBAL_DEFINITIONS_HPP
#define GLOBAL_DEFINITIONS_HPP

/* Error code */
#define BECKHOFF_NO_ERROR 0
#define BECKHOFF_ETHERCAT_COMM_ERROR 1

#define LIDAR_NO_ERROR 0
#define LIDAR_NO_DATA 1

#define CAM_KIRI_NO_ERROR 0
#define CAM_KIRI_FAILED_TO_SET_FOURCC 1
#define CAM_KIRI_FAILED_TO_SET_WIDTH 2
#define CAM_KIRI_FAILED_TO_SET_HEIGHT 3
#define CAM_KIRI_FAILED_TO_SET_FPS 4
#define CAM_KIRI_NO_DATA 11

#define CAM_KANAN_NO_ERROR 0
#define CAM_KANAN_FAILED_TO_SET_FOURCC 1
#define CAM_KANAN_FAILED_TO_SET_WIDTH 2
#define CAM_KANAN_FAILED_TO_SET_HEIGHT 3
#define CAM_KANAN_FAILED_TO_SET_FPS 4
#define CAM_KANAN_NO_DATA 11

#define SINGLE_DETECTION_NO_ERROR 0
#define SINGLE_DETECTION_FAILED_TO_LOAD_CONFIG 1
#define SINGLE_DETECTION_FAILED_TO_SAVE_CONFIG 2
#define SINGLE_DETECTION_FAILED_TO_CONVERT_IMAGE 3
#define SINGLE_DETECTION_FAILED_TO_CLONE_IMAGE 4
#define SINGLE_DETECTION_NO_DATA 5

#define LANE_DETECTION_NO_ERROR 0
#define LANE_DETECTION_FAILED_TO_LOAD_CONFIG 1
#define LANE_DETECTION_FAILED_TO_SAVE_CONFIG 2
#define LANE_DETECTION_FAILED_TO_CONVERT_IMAGE 3
#define LANE_DETECTION_FAILED_TO_CLONE_IMAGE 4
#define LANE_DETECTION_NO_DATA 5

/* Another Definitions */

#endif // GLOBAL_DEFINITIONS_HPP