Detection:
  cam_kanan:
    low_h: 0
    low_l: 183
    low_s: 0
    high_h: 255
    high_l: 255
    high_s: 255
    setpoint_x: 320
    setpoint_y: 140
  cam_kiri:
    low_h: 0
    low_l: 112
    low_s: 0
    high_h: 255
    high_l: 255
    high_s: 255
    setpoint_x: 320
    setpoint_y: 240
  aruco_kanan:
    low_h: 27
    low_l: 153
    low_s: 0
    high_h: 255
    high_l: 255
    high_s: 255
  lane_kanan:
    low_h: 27
    low_l: 153
    low_s: 0
    high_h: 255
    high_l: 255
    high_s: 255